apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: obj2bms-sep30-1
  janus-idp.io/tekton: obj2bms-sep30-1
  backstage.io/kubernetes-id: obj2bms-sep30-1
  backstage.io/kubernetes-namespace: obj2bms-sep30-1 
  app.kubernetes.io/part-of: obj2bms-sep30-1
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
