---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: obj2bms-sep30-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: obj2bms-sep30-1 
  name: obj2bms-sep30-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi